export type sampleDataType = {
  [key: string]: Array<{label: string; value: string}>;
};

export const subdivision: sampleDataType = {
  'Dhaka North': [
    {label: 'Gulshan-0101', value: 'Gulshan-0101'},
    {label: 'Tongi-0102', value: 'Tongi-0102'},
    {label: 'Gazipur-0103', value: 'Gazipur-0103'},
    {label: 'Mymensing-0104', value: 'Mymensing-0104'},
    {label: 'Kishorgonj-0105', value: 'Kishorgonj-0105'},
    {label: 'Netrokona-0106', value: 'Netrokona-0106'},
    {label: 'Sherpur-0107', value: 'Sherpur-0107'},
  ],
  'Dhaka South': [
    {label: 'Dhanmondi-0201', value: 'Dhanmondi-0201'},
    {label: 'Motijheel-0202', value: 'Motijheel-0202'},
    {label: 'Tejgaon-0203', value: 'Tejgaon-0203'},
    {label: 'Narayangonj-0204', value: 'Narayangonj-0204'},
    {label: 'Kotwali-0205', value: 'Kotwali-0205'},
    {label: 'Lalbag-0206', value: 'Lalbag-0206'},
    {label: 'Munshigonj-0207', value: 'Munshigonj-0207'},
    {label: 'Segunbaghica-0208', value: 'Segunbaghica-0208'},
  ],
  'Dhaka East': [
    {label: 'Sutrapur-0301', value: 'Sutrapur-0301'},
    {label: 'Bondar-0302', value: 'Bondar-0302'},
    {label: 'Rupgonj-0303', value: 'Rupgonj-0303'},
    {label: 'Sonargaon-0304', value: 'Sonargaon-0304'},
    {label: 'Siddirgonj-0305', value: 'Siddirgonj-0305'},
    {label: 'Narsingdi-0306', value: 'Narsingdi-0306'},
    {label: 'Demra-0307', value: 'Demra-0307'},
    {label: 'Shampur-0308', value: 'Shampur-0308'},
  ],
  'Dhaka West': [
    {label: 'Mirpur-0401', value: 'Mirpur-0401'},
    {label: 'Mohammadpur-0402', value: 'Mohammadpur-0402'},
    {label: 'Savar-0403', value: 'Savar-0403'},
    {label: 'Dhamrai-0404', value: 'Dhamrai-0404'},
    {label: 'Manikgonj-0405', value: 'Manikgonj-0405'},
    {label: 'Tangail-0406', value: 'Tangail-0406'},
    {label: 'Jamalpur-0407', value: 'Jamalpur-0407'},
  ],
  Chattogram: [
    {label: 'Bandarban-0501', value: 'Bandarban-0501'},
    {label: 'Patiya-0502', value: 'Patiya-0502'},
    {label: 'Agrabad-0503', value: 'Agrabad-0503'},
    {label: 'Chandgaon-0504', value: 'Chandgaon-0504'},
    {label: 'Chattala-0505', value: 'Chattala-0505'},
    {label: 'Rangamati-0506', value: 'Rangamati-0506'},
    {label: "Cox's Bazar-0507", value: "Cox's Bazar-0507"},
    {label: 'Khagrachori-0508', value: 'Khagrachori-0508'},
  ],
};

export const circle: sampleDataType = {
  'Gulshan-0101': [
    {label: 'Circle-1', value: 'Circle-1'},
    {label: 'Circle-2', value: 'Circle-2'},
    {label: 'Circle-3', value: 'Circle-3'},
    {label: 'Circle-4', value: 'Circle-4'},
    {label: 'Circle-5', value: 'Circle-5'},
  ],
  'Tongi-0102': [
    {label: 'Circle-1', value: 'Circle-1'},
    {label: 'Circle-2', value: 'Circle-2'},
    {label: 'Circle-3', value: 'Circle-3'},
    {label: 'Circle-4', value: 'Circle-4'},
    {label: 'Circle-5', value: 'Circle-5'},
  ],
  'Gazipur-0103': [
    {label: 'Circle-1', value: 'Circle-1'},
    {label: 'Circle-2', value: 'Circle-2'},
    {label: 'Circle-3', value: 'Circle-3'},
    {label: 'Circle-4', value: 'Circle-4'},
    {label: 'Circle-5', value: 'Circle-5'},
  ],
  'Mymensing-0104': [
    {label: 'Circle-1', value: 'Circle-1'},
    {label: 'Circle-2', value: 'Circle-2'},
    {label: 'Circle-3', value: 'Circle-3'},
    {label: 'Circle-4', value: 'Circle-4'},
    {label: 'Circle-5', value: 'Circle-5'},
  ],
  'Kishorgonj-0105': [
    {label: 'Circle-1', value: 'Circle-1'},
    {label: 'Circle-2', value: 'Circle-2'},
    {label: 'Circle-3', value: 'Circle-3'},
    {label: 'Circle-4', value: 'Circle-4'},
    {label: 'Circle-5', value: 'Circle-5'},
  ],
  'Netrokona-0106': [
    {label: 'Circle-1', value: 'Circle-1'},
    {label: 'Circle-2', value: 'Circle-2'},
    {label: 'Circle-3', value: 'Circle-3'},
    {label: 'Circle-4', value: 'Circle-4'},
    {label: 'Circle-5', value: 'Circle-5'},
  ],
  'Sherpur-0107': [
    {label: 'Circle-1', value: 'Circle-1'},
    {label: 'Circle-2', value: 'Circle-2'},
    {label: 'Circle-3', value: 'Circle-3'},
    {label: 'Circle-4', value: 'Circle-4'},
    {label: 'Circle-5', value: 'Circle-5'},
  ],
  'Dhanmondi-0201': [
    {label: 'Dhanmondi', value: 'Dhanmondi'},
    {label: 'Rayerbazar', value: 'Rayerbazar'},
    {label: 'Kalabagan', value: 'Kalabagan'},
    {label: 'Nilkhet', value: 'Nilkhet'},
  ],
  'Motijheel-0202': [
    {label: 'Motijheel', value: 'Motijheel'},
    {label: 'Razarbag', value: 'Razarbag'},
    {label: 'Arambag', value: 'Arambag'},
    {label: 'Rampura', value: 'Rampura'},
  ],
  'Tejgaon-0203': [
    {label: 'Tejgaon', value: 'Tejgaon'},
    {label: 'Begunbari', value: 'Begunbari'},
    {label: 'Kawranbazar', value: 'Kawranbazar'},
    {label: 'Firmgate', value: 'Firmgate'},
  ],
  'Narayangonj-0204': [
    {label: 'Narayangonj', value: 'Narayangonj'},
    {label: 'Fatullah', value: 'Fatullah'},
    {label: 'Aliganj', value: 'Aliganj'},
    {label: 'Enayet Nagar', value: 'Enayet Nagar'},
  ],
  'Kotwali-0205': [
    {label: 'Bongshal', value: 'Bongshal'},
    {label: 'Armanitola', value: 'Armanitola'},
    {label: 'Chawkbazar', value: 'Chawkbazar'},
    {label: 'Bakshi Bazar', value: 'Bakshi Bazar'},
  ],
  'Lalbag-0206': [
    {label: 'Azimpur', value: 'Azimpur'},
    {label: 'Imamgonj', value: 'Imamgonj'},
    {label: 'Keranigonj', value: 'Keranigonj'},
    {label: 'Hasnabad', value: 'Hasnabad'},
  ],
  'Munshigonj-0207': [
    {label: 'Munshigonj', value: 'Munshigonj'},
    {label: 'Gojaria', value: 'Gojaria'},
    {label: 'Srinagar', value: 'Srinagar'},
    {label: 'Sirajdikhan', value: 'Sirajdikhan'},
  ],
  'Segunbaghica-0208': [
    {label: 'Segunbaghica', value: 'Segunbaghica'},
    {label: 'Siddeshwari', value: 'Siddeshwari'},
    {label: 'Fulbaria', value: 'Fulbaria'},
    {label: 'Palton', value: 'Palton'},
  ],
  'Sutrapur-0301': [
    {label: 'Gandaria', value: 'Gandaria'},
    {label: 'Mirhazaribag', value: 'Mirhazaribag'},
    {label: 'Postugola', value: 'Postugola'},
    {label: 'Sutrapur', value: 'Sutrapur'},
  ],
  'Bondar-0302': [
    {label: 'Bondar', value: 'Bondar'},
    {label: 'Kachpur', value: 'Kachpur'},
    {label: 'Dhamgarh', value: 'Dhamgarh'},
    {label: 'Shimrail', value: 'Shimrail'},
  ],
  'Rupgonj-0303': [
    {label: 'Rupgonj', value: 'Rupgonj'},
    {label: 'Tarabo', value: 'Tarabo'},
    {label: 'Vulta', value: 'Vulta'},
    {label: 'Murapara', value: 'Murapara'},
  ],
  'Sonargaon-0304': [
    {label: 'Sonargaon', value: 'Sonargaon'},
    {label: 'Madanpur', value: 'Madanpur'},
    {label: 'Mugrapara', value: 'Mugrapara'},
    {label: 'Araihajar', value: 'Araihajar'},
  ],
  'Siddirgonj-0305': [
    {label: 'Siddirgonj', value: 'Siddirgonj'},
    {label: 'Hirajhil', value: 'Hirajhil'},
    {label: 'Mouchak', value: 'Mouchak'},
    {label: 'Jalcuri', value: 'Jalcuri'},
  ],
  'Narsingdi-0306': [
    {label: 'Narsingdi', value: 'Narsingdi'},
    {label: 'Sibpur', value: 'Sibpur'},
    {label: 'Ghorasal', value: 'Ghorasal'},
    {label: 'Bhairab', value: 'Bhairab'},
  ],
  'Demra-0307': [
    {label: 'Demra', value: 'Demra'},
    {label: 'Rayerbag', value: 'Rayerbag'},
    {label: 'Tikatuli', value: 'Tikatuli'},
    {label: 'Konapara', value: 'Konapara'},
  ],
  'Shampur-0308': [
    {label: 'Shampur', value: 'Shampur'},
    {label: 'Dania', value: 'Dania'},
    {label: 'Dhaleshar', value: 'Dhaleshar'},
    {label: 'Kadamtali', value: 'Kadamtali'},
  ],
  'Mirpur-0401': [
    {label: 'Pollabi Circle-1', value: 'Pollabi Circle-1'},
    {label: 'Pollabi Circle-2', value: 'Pollabi Circle-2'},
    {label: 'Kazipara', value: 'Kazipara'},
    {label: 'Kafrul', value: 'Kafrul'},
    {label: 'Kallyanpur', value: 'Kallyanpur'},
  ],
  'Mohammadpur-0402': [
    {label: 'Mohammadpur', value: 'Mohammadpur'},
    {label: 'Razabazar', value: 'Razabazar'},
    {label: 'Shyamoli', value: 'Shyamoli'},
  ],
  'Savar-0403': [
    {label: 'Hemayatpur', value: 'Hemayatpur'},
    {label: 'Savar', value: 'Savar'},
    {label: 'Dhamsona', value: 'Dhamsona'},
    {label: 'Rajashon', value: 'Rajashon'},
    {label: 'Ashulia', value: 'Ashulia'},
  ],
  'Dhamrai-0404': [
    {label: 'Dhamrai', value: 'Dhamrai'},
    {label: 'Singair', value: 'Singair'},
  ],
  'Manikgonj-0405': [
    {label: 'Manikgonj', value: 'Manikgonj'},
    {label: 'Shibaloy', value: 'Shibaloy'},
  ],
  'Tangail-0406': [
    {label: 'Circle-1', value: 'Circle-1'},
    {label: 'Circle-2', value: 'Circle-2'},
    {label: 'Circle-3', value: 'Circle-3'},
  ],
  'Jamalpur-0407': [
    {label: 'Circle-1', value: 'Circle-1'},
    {label: 'Circle-2', value: 'Circle-2'},
  ],
  'Bandarban-0501': [
    {label: 'Bandarban', value: 'Bandarban'},
    {label: 'Lama', value: 'Lama'},
  ],
  'Patiya-0502': [
    {label: 'Patiya', value: 'Patiya'},
    {label: 'Karnafuly', value: 'Karnafuly'},
    {label: 'Boalkhali', value: 'Boalkhali'},
  ],
  'Agrabad-0503': [
    {label: 'Agrabad', value: 'Agrabad'},
    {label: 'Potenga', value: 'Potenga'},
    {label: 'Sadarghat', value: 'Sadarghat'},
    {label: 'Kotwali', value: 'Kotwali'},
  ],
  'Chandgaon-0504': [
    {label: 'Bakolia', value: 'Bakolia'},
    {label: 'Kalurghat', value: 'Kalurghat'},
    {label: 'Kaptai', value: 'Kaptai'},
    {label: 'Nasirabad', value: 'Nasirabad'},
  ],
  'Chattala-0505': [
    {label: 'Halishahar', value: 'Halishahar'},
    {label: 'Pahartali', value: 'Pahartali'},
    {label: 'Foujdarhat', value: 'Foujdarhat'},
    {label: 'Panchlaish', value: 'Panchlaish'},
  ],
  'Rangamati-0506': [
    {label: 'Rangamati', value: 'Rangamati'},
    {label: 'Rangunia', value: 'Rangunia'},
  ],
  "Cox's Bazar-0507": [
    {label: "Cox's Bazar", value: "Cox's Bazar"},
    {label: 'Chakaria', value: 'Chakaria'},
    {label: 'Teknaf', value: 'Teknaf'},
  ],
  'Khagrachori-0508': [
    {label: 'Khagrachori', value: 'Khagrachori'},
    {label: 'Sitakunda', value: 'Sitakunda'},
  ],
};
