export interface ApplicationData {
  date: Date;
  binNumber: string;
  commissioneRate: string;
  division: string;
  subDivision: string;
  circle: string;
  shopName: string;
  brandName: string;
  areaOrshoppingMall: string;
  businessRegisteredAddress: string;
  outletAddress: string;
  binHolderNid: number | null;
  binHolderName: string;
  binHolderMobile: number | null;
  binHolderEmail: string;
  businessStartDate: Date;
  category: string;
  mushak: string;
  subCategory: string;
  latitude: number;
  longitude: number;
  numberOfOutlet: number | null;
  numberOfCounter: number | null;
  differentBin: string;
  transactionType: string;
  posSoftwareProvider: string;
  nrbApproved: string;
  thirdPartyName: string;
  monthlyAverageSales: number | null;
  monthlyAverageCustomer: number | null;
  onlineSaleAvailable: string;
  onlineSaleParcent: number | null;
  onlineOrderMode: string;
  productInfo: string;
  productName: string;
  productUnit: string;
  unitPrice: number | null;
  vatParcent: number | null;
  sdPercent: number | null;
  priceIncludingVat: number;
  priceExcludingVat: number;
  stockKeeping: string;
  posSoftware: string;
  posPrinter: string;
  pcOrLaptop: string;
  router: string;
  networking: string;
  surveillance: string;
  mobileOperator: string;
  operatorCoverage: string;
  shopPic: HTMLImageElement | null;
  binCertificate: HTMLImageElement | null;
  itemList: HTMLImageElement[];
}
